CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE TABLE "ContactMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" character varying(120) NOT NULL,
        "Phone" character varying(20) NOT NULL,
        "Email" character varying(200) NOT NULL,
        "Message" character varying(1000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ContactMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE TABLE "PriceItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(160) NOT NULL,
        "PriceText" character varying(80) NOT NULL,
        "Note" character varying(300) NOT NULL,
        "SortOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_PriceItems" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE TABLE "Roles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(80) NOT NULL,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE TABLE "Services" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(160) NOT NULL,
        "Description" character varying(600) NOT NULL,
        "IsActive" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_Services" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE TABLE "StoreSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BrandName" character varying(160) NOT NULL,
        "Address" character varying(300) NOT NULL,
        "Hotline" character varying(30) NOT NULL,
        "ZaloUrl" character varying(200) NOT NULL,
        "FacebookUrl" character varying(200) NOT NULL,
        "OpeningHours" character varying(120) NOT NULL,
        "DeliveryPolicy" character varying(300) NOT NULL,
        CONSTRAINT "PK_StoreSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserName" character varying(80) NOT NULL,
        "PasswordHash" character varying(200) NOT NULL,
        "RoleId" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE TABLE "Bookings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerName" character varying(120) NOT NULL,
        "Phone" character varying(20) NOT NULL,
        "Address" character varying(500) NOT NULL,
        "AddressNote" character varying(300) NOT NULL,
        "ServiceId" integer NOT NULL,
        "EstimatedWeight" numeric(18,2),
        "PickupTime" timestamp with time zone NOT NULL,
        "Note" character varying(1000) NOT NULL,
        "Latitude" double precision,
        "Longitude" double precision,
        "DistanceKm" double precision,
        "RequiresDistanceConfirmation" boolean NOT NULL,
        "Status" character varying(40) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Bookings_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE TABLE "BookingDetails" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BookingId" integer NOT NULL,
        "ItemName" character varying(160) NOT NULL,
        "Quantity" integer NOT NULL,
        "Note" character varying(200) NOT NULL,
        CONSTRAINT "PK_BookingDetails" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BookingDetails_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    INSERT INTO "PriceItems" ("Id", "IsActive", "Name", "Note", "PriceText", "SortOrder")
    VALUES (1, TRUE, 'Giặt thường', 'Phù hợp quần áo thường ngày', '15.000đ/kg', 1);
    INSERT INTO "PriceItems" ("Id", "IsActive", "Name", "Note", "PriceText", "SortOrder")
    VALUES (2, TRUE, 'Giặt + sấy thơm', 'Sấy khô, thơm lâu', '25.000đ/kg', 2);
    INSERT INTO "PriceItems" ("Id", "IsActive", "Name", "Note", "PriceText", "SortOrder")
    VALUES (3, TRUE, 'Giặt hấp vest / áo khoác / đồ cao cấp', 'Xử lý theo chất liệu', 'Từ 50.000đ/cái', 3);
    INSERT INTO "PriceItems" ("Id", "IsActive", "Name", "Note", "PriceText", "SortOrder")
    VALUES (4, TRUE, 'Giặt chăn ga gối nệm', 'Tùy kích thước', '40.000đ - 80.000đ/bộ', 4);
    INSERT INTO "PriceItems" ("Id", "IsActive", "Name", "Note", "PriceText", "SortOrder")
    VALUES (5, TRUE, 'Giặt giày', 'Vệ sinh, khử mùi', 'Từ 50.000đ/đôi', 5);
    INSERT INTO "PriceItems" ("Id", "IsActive", "Name", "Note", "PriceText", "SortOrder")
    VALUES (6, TRUE, 'Ủi đồ', 'Ủi phẳng, treo gọn', 'Từ 10.000đ/cái', 6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    INSERT INTO "Roles" ("Id", "Name")
    VALUES (1, 'Admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    INSERT INTO "Services" ("Id", "Description", "IsActive", "Name", "SortOrder")
    VALUES (1, 'Phân loại màu, giặt sạch và sấy thơm cho nhu cầu hằng ngày.', TRUE, 'Giặt sấy theo kg', 1);
    INSERT INTO "Services" ("Id", "Description", "IsActive", "Name", "SortOrder")
    VALUES (2, 'Xử lý vest, áo khoác và đồ cao cấp cần chăm sóc kỹ.', TRUE, 'Giặt hấp / giặt khô', 2);
    INSERT INTO "Services" ("Id", "Description", "IsActive", "Name", "SortOrder")
    VALUES (3, 'Làm sạch chăn ga, gối, nệm mỏng theo từng bộ.', TRUE, 'Giặt chăn ga gối nệm', 3);
    INSERT INTO "Services" ("Id", "Description", "IsActive", "Name", "SortOrder")
    VALUES (4, 'Vệ sinh giày, khử mùi và làm khô đúng cách.', TRUE, 'Giặt giày dép', 4);
    INSERT INTO "Services" ("Id", "Description", "IsActive", "Name", "SortOrder")
    VALUES (5, 'Ủi thẳng áo sơ mi, quần tây, đồng phục và trang phục công sở.', TRUE, 'Ủi đồ', 5);
    INSERT INTO "Services" ("Id", "Description", "IsActive", "Name", "SortOrder")
    VALUES (6, 'Nhận và trả đồ trong khu vực bán kính 3km.', TRUE, 'Giao nhận tận nhà', 6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    INSERT INTO "StoreSettings" ("Id", "Address", "BrandName", "DeliveryPolicy", "FacebookUrl", "Hotline", "OpeningHours", "ZaloUrl")
    VALUES (1, 'Địa chỉ cửa hàng đang cập nhật', 'Giặt Sấy Hiệp', 'Hỗ trợ giao nhận trong bán kính 3km', 'https://facebook.com/', '0900 000 000', '7:00 - 21:00 hằng ngày', 'https://zalo.me/0900000000');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    INSERT INTO "Users" ("Id", "IsActive", "PasswordHash", "RoleId", "UserName")
    VALUES (1, TRUE, 'demo-change-me', 1, 'admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE INDEX "IX_BookingDetails_BookingId" ON "BookingDetails" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE INDEX "IX_Bookings_ServiceId" ON "Bookings" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    PERFORM setval(
        pg_get_serial_sequence('"PriceItems"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "PriceItems") + 1,
            nextval(pg_get_serial_sequence('"PriceItems"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Roles"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Roles") + 1,
            nextval(pg_get_serial_sequence('"Roles"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Services"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Services") + 1,
            nextval(pg_get_serial_sequence('"Services"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"StoreSettings"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "StoreSettings") + 1,
            nextval(pg_get_serial_sequence('"StoreSettings"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Users"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Users") + 1,
            nextval(pg_get_serial_sequence('"Users"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260612022618_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260612022618_InitialPostgres', '10.0.5');
    END IF;
END $EF$;
COMMIT;

